# Generated by Django 4.2.18 on 2025-02-21 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('idAcudiente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=100)),
                ('contrasena', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Administrativos',
            fields=[
                ('idAdministrativo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('ciclo', models.CharField(max_length=12)),
                ('correo', models.EmailField(max_length=100)),
                ('contrasena', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('idEstudiante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('contrasena', models.CharField(max_length=100)),
                ('faltasTipo1', models.IntegerField(default=0)),
                ('faltasTipo2', models.IntegerField(default=0)),
                ('faltasTipo3', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Faltas',
            fields=[
                ('idFalta', models.AutoField(primary_key=True, serialize=False)),
                ('tipoFalta', models.IntegerField()),
                ('descripcion', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('idGrado', models.AutoField(primary_key=True, serialize=False)),
                ('grado', models.CharField(max_length=3)),
                ('ciclo', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('idObservacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('comentario', models.TextField(max_length=1000)),
                ('idAdministrativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='Observador.administrativos')),
                ('idEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='Observador.estudiante')),
                ('idFalta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='Observador.faltas')),
                ('idGrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='Observador.grado')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='Observador.grado'),
        ),
        migrations.CreateModel(
            name='Citaciones',
            fields=[
                ('idCitacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('idAcudiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citaciones', to='Observador.acudiente')),
                ('idEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citaciones', to='Observador.estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='acudiente',
            name='idEstudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acudientes', to='Observador.estudiante'),
        ),
    ]
