# Generated by Django 4.2.18 on 2025-02-21 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Observador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grado',
            name='grado',
        ),
    ]
