# Generated by Django 5.1.1 on 2025-02-23 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observador', '0002_remove_grado_grado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='grado',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='idGrado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Observador.grado'),
        ),
        migrations.AddField(
            model_name='grado',
            name='grado',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
