# Generated by Django 4.2.18 on 2025-02-21 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Observador', '0002_remove_grado_grado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grados',
            fields=[
                ('idGrado', models.AutoField(primary_key=True, serialize=False)),
                ('grado', models.CharField(max_length=3)),
                ('ciclo', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'Grados',
            },
        ),
        migrations.RenameModel(
            old_name='Acudiente',
            new_name='Acudientes',
        ),
        migrations.DeleteModel(
            name='Grado',
        ),
        migrations.AlterModelTable(
            name='acudientes',
            table='Acudientes',
        ),
        migrations.AlterModelTable(
            name='administrativos',
            table='Administrativos',
        ),
        migrations.AlterModelTable(
            name='citaciones',
            table='Citaciones',
        ),
        migrations.AlterModelTable(
            name='estudiantes',
            table='Estudiantes',
        ),
        migrations.AlterModelTable(
            name='faltas',
            table='Faltas',
        ),
        migrations.AlterModelTable(
            name='observaciones',
            table='Observaciones',
        ),
        migrations.RenameModel(
            old_name='Estudiante',
            new_name='Estudiantes',
        ),
        migrations.RenameModel(
            old_name='Observacion',
            new_name='Observaciones',
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='Observador.grados'),
        ),
        migrations.AlterField(
            model_name='observaciones',
            name='idGrado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='Observador.grados'),
        ),
    ]
