# Generated by Django 5.1.1 on 2025-02-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observador', '0003_remove_estudiante_grado_estudiante_idgrado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grado',
            name='grado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
