# Generated by Django 5.1.1 on 2025-02-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observador', '0004_alter_grado_grado'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='identificacion',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
