# Generated by Django 5.1.1 on 2025-02-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observador', '0005_estudiante_identificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='tipoDocumento',
            field=models.CharField(choices=[('T.I.', 'Tarjeta de Identidad'), ('C.C.', 'Cedula de Ciudadanía'), ('C.E.', 'Cedula de Extranjería')], default='T.I.', max_length=4),
        ),
    ]
