# Generated by Django 5.1.1 on 2025-02-23 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Observador', '0006_estudiante_tipodocumento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='identificacion',
            new_name='documento',
        ),
    ]
