# Generated by Django 4.2.18 on 2025-02-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observador', '0007_rename_identificacion_estudiante_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='acudiente',
            name='documento',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='acudiente',
            name='tipoDocumento',
            field=models.CharField(choices=[('T.I.', 'Tarjeta de Identidad'), ('C.C.', 'Cedula de Ciudadanía'), ('C.E.', 'Cedula de Extranjería')], default='C.C.', max_length=4),
        ),
    ]
