# Generated by Django 5.1.1 on 2025-02-27 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Observador', '0008_acudiente_documento_acudiente_tipodocumento'),
        ('Observador', '0009_estudiante_idcolegio_faltas_idcolegio_and_more'),
    ]

    operations = [
    ]
