# Generated by Django 5.1.1 on 2025-02-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observador', '0010_merge_20250226_2128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grado',
            options={},
        ),
        migrations.AlterField(
            model_name='grado',
            name='grado',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
