# Generated by Django 4.2.20 on 2025-03-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observador', '0012_faltas_falta_alter_administrativos_cargo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observacion',
            name='idGrado',
        ),
        migrations.AlterField(
            model_name='administrativos',
            name='cargo',
            field=models.CharField(choices=[('Profesor', 'Profesor'), ('Directivo', 'Directivo')], default='profesor', max_length=9),
        ),
    ]
