# Generated by Django 4.2.20 on 2025-03-27 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observador', '0015_administrativos_idcolegio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrativos',
            name='ciclo',
        ),
        migrations.AlterField(
            model_name='administrativos',
            name='cargo',
            field=models.CharField(choices=[('Ciclo Inicial', 'Ciclo Inicial'), ('Ciclo 1', 'Ciclo 1'), ('Ciclo 2', 'Ciclo 2'), ('Ciclo 3', 'Ciclo 3'), ('Ciclo 4', 'Ciclo 4')], default='Ciclo Inicial', max_length=13),
        ),
    ]
