# Generated by Django 4.2.20 on 2025-03-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observador', '0017_administrativos_ciclo_alter_administrativos_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='correo',
            field=models.EmailField(default='hola@gmail.com', max_length=100),
        ),
    ]
