# Generated by Django 4.2.20 on 2025-03-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observador', '0018_estudiante_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='correo',
            field=models.EmailField(max_length=100),
        ),
    ]
