# Generated by Django 4.2.18 on 2025-04-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observador', '0019_alter_estudiante_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrativos',
            name='idColegio',
        ),
        migrations.RemoveField(
            model_name='citaciones',
            name='asistencia',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='correo',
        ),
        migrations.AlterField(
            model_name='administrativos',
            name='cargo',
            field=models.CharField(choices=[('profesor', 'Profesor'), ('directivo', 'Directivo')], default='profesor', max_length=9),
        ),
        migrations.AlterField(
            model_name='administrativos',
            name='ciclo',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
