# Generated by Django 4.2.18 on 2025-04-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observador', '0020_remove_administrativos_idcolegio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='correo',
            field=models.EmailField(default='hola@gmail.com', max_length=100),
        ),
    ]
