# Generated by Django 4.2.18 on 2025-04-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observador', '0021_estudiante_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='correo',
            field=models.EmailField(max_length=100),
        ),
    ]
