# Generated by Django 4.2.18 on 2025-04-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observador', '0022_alter_estudiante_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='urlImagenPerfil',
            field=models.CharField(default='', max_length=256),
        ),
    ]
