# Generated by Django 4.2.18 on 2025-04-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observador', '0023_estudiante_urlimagenperfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='urlImagenPerfil',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
