# Generated by Django 4.2.18 on 2025-04-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observador', '0024_remove_estudiante_urlimagenperfil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='edad',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fechaNacimiento',
            field=models.DateField(null=True),
        ),
    ]
