# Generated by Django 4.2.20 on 2025-05-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observador', '0025_remove_estudiante_edad_estudiante_fechanacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenRestablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=100)),
                ('fecha_expiracion', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Token de restablecimiento',
                'verbose_name_plural': 'Tokens de restablecimiento',
            },
        ),
    ]
