# Generated by Django 4.2.20 on 2025-05-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observador', '0026_tokenrestablecimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='totalFaltas',
            field=models.IntegerField(default=0),
        ),
    ]
