# Generated by Django 4.2.20 on 2025-05-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observador', '0027_estudiante_totalfaltas'),
    ]

    operations = [
        migrations.AddField(
            model_name='citaciones',
            name='asistencia',
            field=models.BooleanField(null=True),
        ),
    ]
